import 'server-only'
import crypto from 'node:crypto'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { env } from './env'
import { encryptBytes, decryptBytes } from './crypto'

/**
 * Encrypted-at-rest file storage for sensitive documents (passports, licences,
 * payment proofs). Files are AES-256-GCM encrypted (shared cipher in lib/crypto.ts)
 * and written outside the web root; they are ONLY ever served through an
 * access-controlled route handler that decrypts in memory. The nginx/web server
 * must never expose STORAGE_DIR statically.
 */

function storageRoot(): string {
  return path.resolve(process.cwd(), env.storageDir)
}

function safeKeyPath(storageKey: string): string {
  // storageKey is generated by us (below); reject traversal defensively.
  if (storageKey.includes('..') || path.isAbsolute(storageKey)) {
    throw new Error('Invalid storage key')
  }
  return path.join(storageRoot(), storageKey)
}

export interface EncryptResult {
  storageKey: string
  iv: string
  authTag: string
  size: number
}

/** Encrypt & persist bytes. Returns the storage key + iv/authTag to save in DB. */
export async function saveEncrypted(bytes: Buffer, ext = ''): Promise<EncryptResult> {
  const { data, iv, authTag } = encryptBytes(bytes)

  const id = crypto.randomBytes(16).toString('hex')
  const yyyymm = new Date().toISOString().slice(0, 7).replace('-', '/')
  const storageKey = `${yyyymm}/${id}${ext ? '.' + ext.replace(/[^a-z0-9]/gi, '') : ''}.enc`
  const dest = safeKeyPath(storageKey)

  await fs.mkdir(path.dirname(dest), { recursive: true })
  await fs.writeFile(dest, data)

  return { storageKey, iv, authTag, size: bytes.length }
}

/** Decrypt a stored file in memory. */
export async function readDecrypted(
  storageKey: string,
  ivHex: string,
  authTagHex: string,
): Promise<Buffer> {
  const enc = await fs.readFile(safeKeyPath(storageKey))
  return decryptBytes(enc, ivHex, authTagHex)
}

export async function deleteStored(storageKey: string): Promise<void> {
  await fs.rm(safeKeyPath(storageKey), { force: true })
}
